### ISSUE TITLE
can't unzip in win10

### ISSUE THREAD

**Issue by MarkVdBergh** [PatrickChrist/diabetes60#1]
I've downloaded the data.zip file from Google Drive, but I'm unable to unzip it on Windows 10.

**Comment by sebastian-schlecht** [comment]
Hey, we're on it.

**Comment by MarkVdBergh** [comment]
I downloaded it again but in Ubuntu iso Windows, and there it could unzip some files, but it also ended with an error.

**Comment by sebastian-schlecht** [comment]
I‘m currently uploading a newly zipped version. As my current upstream bandwidth is a bit limited, it might take until tomorrow morning to upload.

**Comment by sebastian-schlecht** [comment]
@MarkVdBergh I've uploaded the raw data again using a different compression library and verified the archive in Windows 10.

**Comment by MarkVdBergh** [comment]
It works now. Many thanks @sebastian-schlecht !

**Comment by sebastian-schlecht** [comment]
You're welcome. Closing this now.
